import { NgxUiLoaderConfig } from "ngx-ui-loader";

export const ngxUiLoaderConfig: NgxUiLoaderConfig  = {
    "bgsColor": "yellow",
    "bgsOpacity": 0.5,
    "bgsPosition": "center-center",
    "bgsSize": 60,
    "bgsType": "ball-spin-clockwise",
    "blur": 5,
    "delay": 0,
    "fastFadeOut": true,
    "fgsColor": "black",
    "fgsPosition": "center-center",
    "fgsSize": 60,
    "fgsType": "ball-spin-clockwise",
    "gap": 24,
    "logoPosition": "center-center",
    "logoSize": 120,
    "logoUrl": "https://www.internetweek.si/wp-content/uploads/2013/10/3fs_logo_rumen_256x.jpg",
    "masterLoaderId": "master",
    "overlayBorderRadius": "0",
    "overlayColor": "rgba(40, 40, 40, 0.8)",
    "pbColor": "yellow",
    "pbDirection": "ltr",
    "pbThickness": 3,
    "hasProgressBar": true,
    "text": "Creating bucket",
    "textColor": "#FFFFFF",
    "textPosition": "center-center",
    "maxTime": -1,
    "minTime": 300
}