version: '3'

services:
  app-dev:
    build:
      context: app/.
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  api-dev:
    build:
      context: api/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/DB.json:/data/DB.json
      - ./api/uploads:/data/uploads
